local BartHIghlight = Instance.new("Highlight")
local HomerHIghlight = Instance.new("Highlight")
local KrustyHIghlight = Instance.new("Highlight")
local MaggieHIghlight = Instance.new("Highlight")
local LisaHIghlight = Instance.new("Highlight")
local MargeHIghlight = Instance.new("Highlight")
local MonsterHIghlight = Instance.new("Highlight")
BartHIghlight.Parent = workspace.Ai.Bart
HomerHIghlight.Parent = workspace.Ai.Homer
KrustyHIghlight.Parent = workspace.Ai.Krusty
MaggieHIghlight.Parent = workspace.Ai.Lisa
LisaHIghlight.Parent = workspace.Ai.Maggie
MargeHIghlight.Parent = workspace.Ai.Marge
MonsterHIghlight.Parent = workspace.Ai.Monster